INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(1,'lineare Notenliste 1',1,20,0,0,0,1,1,0,0,0,0);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(2,'lineare Notenliste 2',1,40,1,1,1,1,1,0,0,0,0);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(3,'Notenliste mit Knicks 1',2,20,0,0,0,1,1,4.4,10,4,16);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(4,'Notenliste mit Knicks 2',2,40,1,1,1,1,1,4.4,20,4,36);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(5,'exponentielle Notenliste 1',3,40,0,0,0,1,1,4.4,20,4,36);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(6,'exponentielle Notenliste 2',3,40,1,1,1,1,1,4.4,20,4,36);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(7,'IHK Notenliste 1',4,40,0,0,0,1,1,4.4,20,4,36);
INSERT INTO markLists(ID,title,type,maxPoints,tenthMarks,halfPoints,dictatMode,viewMode,markMode,customMark,customPoints,bestMarkAt,worstMarkTo) VALUES(8,'IHK Notenliste 2',4,40,1,1,1,1,1,4.4,20,4,36);

INSERT INTO teachers(ID,lastName,firstName,description) VALUES(1,'Max','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(2,'John','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(3,'Anna','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(4,'Horst','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(5,'Gerd','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(6,'Gertrud','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(7,'Kasper','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(8,'Johann','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(9,'Jusuf','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(10,'Wladimir','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(11,'Kevin','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(12,'Urs','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(13,'Ursula','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(14,'Anne','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(15,'Dadde','Mustermann','Beispiel-Lehrer');
INSERT INTO teachers(ID,lastName,firstName,description) VALUES(16,'Hasan','Mustermann','Beispiel-Lehrer');

UPDATE subjects SET teacher=1 WHERE ID=1;
UPDATE subjects SET teacher=2 WHERE ID=2;
UPDATE subjects SET teacher=3 WHERE ID=3;
UPDATE subjects SET teacher=4 WHERE ID=4;
UPDATE subjects SET teacher=5 WHERE ID=5;
UPDATE subjects SET teacher=6 WHERE ID=6;
UPDATE subjects SET teacher=7 WHERE ID=7;
INSERT INTO subjects(ID,title,alias,description,hoursInWeek,isMainSubject,backgroundColor,teacher) VALUES(8,'Betriebswirtschaftslehre','BWL','Profilfach',6,1,'',8);
INSERT INTO subjects(ID,title,alias,description,hoursInWeek,isMainSubject,backgroundColor,teacher) VALUES(9,'Volkswirtschaftslehre','VWL','Profilfach',2,1,'',9);
INSERT INTO subjects(ID,title,alias,description,hoursInWeek,isMainSubject,backgroundColor,teacher) VALUES(10,'Wirtschaftsinformatik','WI','Profilfach',4,1,'',10);

INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'07:30','08:15',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'08:15','09:00',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'09:00','09:20',1);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'09:20','10:05',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'10:05','10:50',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'10:50','11:10',1);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'11:10','11:55',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'11:55','12:40',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'12:40','13:25',1);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'13:25','14:10',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'14:10','14:55',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'14:55','15:15',1);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'16:00','16:45',0);
INSERT INTO hours(ID,start_time,end_time,isBreak) VALUES(1,'16:45','17:30',0);

INSERT INTO classes(ID,title,numberOfPupils) VALUES(1,'Klasse 1',28);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(2,'Klasse 2',29);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(3,'Klasse 3',30);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(4,'Klasse 4',27);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(5,'Klasse 5',22);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(6,'Klasse 6',29);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(7,'Klasse 7',31);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(8,'Klasse 8',27);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(9,'Klasse 9',28);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(10,'Klasse 10',30);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(11,'Klasse 11',25);
INSERT INTO classes(ID,title,numberOfPupils) VALUES(12,'Klasse 12',22);

INSERT INTO years(ID,title) VALUES(1,'Jahr 2019 - 2020');
INSERT INTO years(ID,title) VALUES(2,'Jahr 2018 - 2019');
INSERT INTO years(ID,title) VALUES(3,'Jahr 2017 - 2018');
INSERT INTO years(ID,title) VALUES(4,'Jahr 2016 - 2017');
INSERT INTO years(ID,title) VALUES(5,'Jahr 2015 - 2016');
INSERT INTO years(ID,title) VALUES(6,'Jahr 2014 - 2015');
INSERT INTO years(ID,title) VALUES(7,'Jahr 2013 - 2014');
INSERT INTO years(ID,title) VALUES(8,'Jahr 2012 - 2013');

INSERT INTO plans(ID,title,class,plan_year) VALUES(1,'Klasse 1 Jahr 2012',1,8);
INSERT INTO plans(ID,title,class,plan_year) VALUES(2,'Klasse 12 Jahr 2019',12,1);
INSERT INTO plans(ID,title,class,plan_year) VALUES(3,'Klasse 5 Jahr 2016',5,4);

INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(1,1,1,1,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(2,1,1,2,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(3,1,1,4,2,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(4,1,1,5,2,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(5,1,1,7,3,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(6,1,2,1,3,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(7,1,2,2,3,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(8,1,2,4,4,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(9,1,2,5,4,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(10,1,3,1,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(11,1,3,2,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(12,1,3,4,2,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(13,1,3,5,2,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(14,1,3,1,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(15,1,4,1,3,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(16,1,4,2,3,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(17,1,4,3,4,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(18,1,4,4,4,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(19,1,5,4,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(20,1,5,4,1,1,0,111,0);
INSERT INTO timeTable(ID,plan,day,hour,subject,teacher,class,roomNumber,current_timetable) VALUES(21,1,5,4,1,0,111,0);
